name: binary_repositories
version: 0.0.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Binary repositories allows easy install individual binary files into local repository from the various kinds of external repositories. Also provides an easy access to installed files at runtime.
homepage: https://github.com/mezoni/binary_repositories
dependencies:
  barback: any
  file_utils: any
  path: any
  pub_semver: any
  system_info: any
dev_dependencies:
  build_tools: any
  unittest: any
